name: SSH Access to GitHub Actions Runner

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install SSH server and ngrok
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok
          sudo systemctl start sshd

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

      - name: Configure SSHD
        run: |
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          sudo systemctl restart sshd

      - name: Start ngrok to expose SSH
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok tcp 22 --log=stdout > ngrok.log &

      - name: Get ngrok public URL
        run: |
          sleep 10
          echo 'NGROK LOGS UNTIL NOW:'
          cat ngrok.log
          echo 'API TUNNELS RESULT:'
          curl -s http://localhost:4040/api/tunnels
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

      - name: Print SSH access instructions
        run: |
          NGROK_URL=$(echo ${{ env.NGROK_URL }} | awk -F'//' '{print $2}')
          NGROK_HOST=$(echo $NGROK_URL | awk -F':' '{print $1}')
          NGROK_PORT=$(echo $NGROK_URL | awk -F':' '{print $2}')
          echo "Run the following command to connect:"
          echo "ssh -i ./id_rsa.github_vps -o 'StrictHostKeyChecking=no' -p $NGROK_PORT runner@$NGROK_HOST"

      - name: Keep the job running
        run: sleep 21600 # Keep the job running for 6 hours
