name: SSH Access to GitHub Actions Runner

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

      - name: Configure SSHD
        run: |
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          sudo systemctl restart sshd

      - name: Check SSH server status
        run: sudo systemctl status sshd

      - name: Check open ports
        run: sudo netstat -tuln

      - name: Print SSH access instructions
        run: |
          echo "Run the following command to connect:"
          echo "ssh -vvv -i ./github_actions_key -o 'StrictHostKeyChecking=no' runner@$(curl -s ifconfig.me)"

      - name: Keep the job running
        run: sleep 21600 # Keep the job running for 6 hours
