name: SSH Access to GitHub Actions Runner via Telebit

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          sudo systemctl start sshd

      - name: Install Telebit
        run: |
          npm install -g telebit
          mkdir -p ~/.config/telebit/
          echo '{
            "email": "${{ secrets.TELEBIT_EMAIL }}",
            "agree": true,
            "token": "",
            "relay": "telebit.cloud"
          }' > ~/.config/telebit/telebit.json
          cat ~/.config/telebit/telebit.json
          telebit --config ~/.config/telebit/telebit.json tcp 22

      - name: Get Telebit public URL
        run: |
          sleep 10
          TELEBIT_URL=$(telebit url)
          echo "TELEBIT_URL=$TELEBIT_URL" >> $GITHUB_ENV

      - name: Print SSH access instructions
        run: |
          echo "Telebit URL: ${{ env.TELEBIT_URL }}"
          TELEBIT_HOST=$(echo ${{ env.TELEBIT_URL }} | awk -F'//' '{print $2}' | awk -F':' '{print $1}')
          TELEBIT_PORT=$(echo ${{ env.TELEBIT_URL }} | awk -F':' '{print $2}')
          echo "Run the following command to connect:"
          echo "ssh -i ./id_rsa.github_vps -o 'StrictHostKeyChecking=no' -p $TELEBIT_PORT runner@$TELEBIT_HOST"

      - name: Keep the job running
        run: sleep 21600 # Keep the job running for 6 hours
