name: SSH Access to GitHub Actions Runner

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install SSH server and ngrok
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys

      - name: Configure SSHD
        run: |
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          sudo systemctl restart sshd

      - name: Start ngrok to expose SSH
        run: |
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok tcp 22 &

      - name: Print ngrok SSH access instructions
        run: |
          sleep 5
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Run the following command to connect:"
          echo "ssh -i ./id_rsa.github_vps -o 'StrictHostKeyChecking=no' runner@${NGROK_URL#tcp://}"

      - name: Keep the job running
        run: sleep 21600 # Keep the job running for 6 hours
